### ISSUE TITLE
Angular9 compilation error

### ISSUE THREAD

**Issue by DowsingUK** [citycide/trilogy#100]
I ran npm i trilogy and npm i sql.js 

and when I try:

import { connect } from 'trilogy'
 
I got these errors: (The whole project it's working with no errors until I imported trilogy)

ERROR in node_modules/runtypes/lib/runtype.d.ts:11:29 - error TS1005: ';' expected.

11     assert(x: any): asserts x is A;
                               ~
node_modules/runtypes/lib/runtype.d.ts:11:31 - error TS1005: ';' expected.

11     assert(x: any): asserts x is A;
                                 ~~
node_modules/runtypes/lib/runtype.d.ts:11:34 - error TS1005: ';' expected.

11     assert(x: any): asserts x is A;
                                    ~
node_modules/runtypes/lib/runtype.d.ts:16:12 - error TS1005: ',' expected.

16     check(x: any): A;
              ~
node_modules/runtypes/lib/runtype.d.ts:16:18 - error TS1005: ';' expected.

16     check(x: any): A;
                    ~
node_modules/runtypes/lib/runtype.d.ts:21:15 - error TS1005: ',' expected.

21     validate(x: any): Result<A>;
                 ~
node_modules/runtypes/lib/runtype.d.ts:21:21 - error TS1005: ';' expected.

21     validate(x: any): Result<A>;
                       ~
node_modules/runtypes/lib/runtype.d.ts:21:32 - error TS1005: '(' expected.

21     validate(x: any): Result<A>;
                                  ~
node_modules/runtypes/lib/runtype.d.ts:25:12 - error TS1005: ',' expected.

25     guard(x: any): x is A;
              ~
node_modules/runtypes/lib/runtype.d.ts:25:18 - error TS1005: ';' expected.

25     guard(x: any): x is A;
                    ~
node_modules/runtypes/lib/runtype.d.ts:25:22 - error TS1005: ';' expected.

25     guard(x: any): x is A;
                        ~~
node_modules/runtypes/lib/runtype.d.ts:25:25 - error TS1005: ';' expected.

25     guard(x: any): x is A;
                           ~
node_modules/runtypes/lib/runtype.d.ts:29:25 - error TS1005: '?' expected.

29     Or<B extends Runtype>(B: B): Union2<this, B>;
                           ~
node_modules/runtypes/lib/runtype.d.ts:29:28 - error TS1005: ',' expected.

29     Or<B extends Runtype>(B: B): Union2<this, B>;
                              ~
node_modules/runtypes/lib/runtype.d.ts:29:32 - error TS1005: ';' expected.

29     Or<B extends Runtype>(B: B): Union2<this, B>;
                                  ~
node_modules/runtypes/lib/runtype.d.ts:29:49 - error TS1005: '(' expected.

29     Or<B extends Runtype>(B: B): Union2<this, B>;
                                                   ~
node_modules/runtypes/lib/runtype.d.ts:33:26 - error TS1005: '?' expected.

33     And<B extends Runtype>(B: B): Intersect2<this, B>;
                            ~
node_modules/runtypes/lib/runtype.d.ts:33:29 - error TS1005: ',' expected.

33     And<B extends Runtype>(B: B): Intersect2<this, B>;
                               ~
node_modules/runtypes/lib/runtype.d.ts:33:33 - error TS1005: ';' expected.

33     And<B extends Runtype>(B: B): Intersect2<this, B>;
                                   ~
node_modules/runtypes/lib/runtype.d.ts:33:54 - error TS1005: '(' expected.

33     And<B extends Runtype>(B: B): Intersect2<this, B>;
                                                        ~
node_modules/runtypes/lib/runtype.d.ts:47:22 - error TS1005: ';' expected.

47     withConstraint<T extends Static<this>, K = unknown>(constraint: ConstraintCheck<this>, options?: {
                        ~~~~~~~
node_modules/runtypes/lib/runtype.d.ts:47:42 - error TS1109: Expression expected.

47     withConstraint<T extends Static<this>, K = unknown>(constraint: ConstraintCheck<this>, options?: {
                                            ~
node_modules/runtypes/lib/runtype.d.ts:47:67 - error TS1005: ')' expected.

47     withConstraint<T extends Static<this>, K = unknown>(constraint: ConstraintCheck<this>, options?: {
                                                                     ~
node_modules/runtypes/lib/runtype.d.ts:47:90 - error TS1109: Expression expected.

47     withConstraint<T extends Static<this>, K = unknown>(constraint: ConstraintCheck<this>, options?: {
                                                                                            ~
node_modules/runtypes/lib/runtype.d.ts:47:100 - error TS1109: Expression expected.

47     withConstraint<T extends Static<this>, K = unknown>(constraint: ConstraintCheck<this>, options?: {
                                                                                                      ~
node_modules/runtypes/lib/runtype.d.ts:48:22 - error TS1005: ',' expected.

48         name?: string;
                        ~
node_modules/runtypes/lib/runtype.d.ts:49:17 - error TS1005: ',' expected.

49         args?: K;
                   ~
node_modules/runtypes/lib/runtype.d.ts:50:6 - error TS1005: ';' expected.

50     }): Constraint<this, T, K>;
        ~
node_modules/runtypes/lib/runtype.d.ts:50:7 - error TS1128: Declaration or statement expected.

50     }): Constraint<this, T, K>;
         ~
node_modules/runtypes/lib/runtype.d.ts:50:31 - error TS1005: '(' expected.

50     }): Constraint<this, T, K>;
                                 ~
node_modules/runtypes/lib/runtype.d.ts:66:17 - error TS1005: ';' expected.

66     withGuard<T extends Static<this>, K = unknown>(guard: (x: Static<this>) => x is T, options?: {
                   ~~~~~~~
node_modules/runtypes/lib/runtype.d.ts:66:37 - error TS1109: Expression expected.

66     withGuard<T extends Static<this>, K = unknown>(guard: (x: Static<this>) => x is T, options?: {
                                       ~
node_modules/runtypes/lib/runtype.d.ts:66:57 - error TS1005: ')' expected.

66     withGuard<T extends Static<this>, K = unknown>(guard: (x: Static<this>) => x is T, options?: {
                                                           ~
node_modules/runtypes/lib/runtype.d.ts:66:82 - merror TS1005: ';' expected.

66     withGuard<T extends Static<this>, K = unknown>(guard: (x: Static<this>) => x is T, options?: {
                                                                                    ~~
node_modules/runtypes/lib/runtype.d.ts:66:85 - error TS1005: ';' expected.

66     withGuard<T extends Static<this>, K = unknown>(guard: (x: Static<this>) => x is T, options?: {
                                                                                       ~
node_modules/runtypes/lib/runtype.d.ts:66:96 - error TS1109: Expression expected.

66     withGuard<T extends Static<this>, K = unknown>(guard: (x: Static<this>) => x is T, options?: {
                                                                                                  ~
node_modules/runtypes/lib/runtype.d.ts:67:22 - error TS1005: ',' expected.

67         name?: string;
                        ~
node_modules/runtypes/lib/runtype.d.ts:68:17 - error TS1005: ',' expected.

68         args?: K;
                   ~
node_modules/runtypes/lib/runtype.d.ts:69:6 - error TS1005: ';' expected.

69     }): Constraint<this, T, K>;
        ~
node_modules/runtypes/lib/runtype.d.ts:69:7 - error TS1128: Declaration or statement expected.

69     }): Constraint<this, T, K>;
         ~
node_modules/runtypes/lib/runtype.d.ts:69:31 - error TS1005: '(' expected.

69     }): Constraint<this, T, K>;
                                 ~
node_modules/runtypes/lib/runtype.d.ts:73:31 - error TS1005: '?' expected.

73     withBrand<B extends string>(brand: B): Brand<B, this>;
                                 ~
node_modules/runtypes/lib/runtype.d.ts:73:38 - error TS1005: ',' expected.

73     withBrand<B extends string>(brand: B): Brand<B, this>;
                                        ~
node_modules/runtypes/lib/runtype.d.ts:73:42 - error TS1005: ';' expected.

73     withBrand<B extends string>(brand: B): Brand<B, this>;
                                            ~
node_modules/runtypes/lib/runtype.d.ts:73:58 - error TS1005: '(' expected.

73     withBrand<B extends string>(brand: B): Brand<B, this>;
                                                            ~
node_modules/runtypes/lib/runtype.d.ts:79:1 - error TS1128: Declaration or statement expected.

79 }

**Comment by citycide** [comment]
Hey @DowsingUK, this is likely to be related to your TypeScript version or configuration. All these errors point to the definitions for trilogy's `runtypes` dependency.

Please use the issue template in the future, it helps debug these things. Could you share your package.json (at least your dep/dev dep versions)? Better yet, provide a repo that reproduces the issue.

**Comment by DowsingUK** [comment]
package.json

{
    "name": "app",
    "version": "1.0.2",
    "license": "",
    "scripts": {
        "ng": "ng",
        "start": "ng serve --open"
    },
    "dependencies": {
        "@angular/core": "9.0.0",
        "@angular/material": "9.0.0",
        "rxjs": "6.5.2",
        "sql.js": "1.2.2",
        "trilogy": "2.0.2",
        "web-animations-js": "2.3.2",
        "zone.js": "0.9.1"
    },
    "devDependencies": {
        "@types/lodash": "4.14.136",
        "@types/node": "8.10.60",
    }
}

**Comment by DowsingUK** [comment]
tsconfig.json

{
    "compileOnSave": false,
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "baseUrl": "./src",
        "outDir": "./dist/",
        "sourceMap": true,
        "declaration": false,
        "downlevelIteration": true,
        "experimentalDecorators": true,
        "module": "esnext",
        "moduleResolution": "node",
        "importHelpers": true,
        "target": "es2015",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2018",
            "dom"
        ],
    },
    "angularCompilerOptions": {
        "fullTemplateTypeCheck": false,
        "strictInjectionParameters": false
    }
}

**Comment by citycide** [comment]
Hmm I don't see a TypeScript version anywhere. I think you need 3.7+ in order to support the assertion functions that `runtypes` uses. Try `npm ls typescript` and see what's installed, or just do `npm i typescript@latest`.

**Comment by DowsingUK** [comment]
I had typescript@3.4.5 I installed last and it's working now, thank you

**Comment by citycide** [comment]
Great to hear, enjoy :smile:
