### ISSUE TITLE
timestamps don't create

### ISSUE THREAD

**Issue by c43721** [citycide/trilogy#110]
## description

Using `timestamps: true` on a model does not create the timestamps on the table, and will error when creating a new object.

### steps to reproduce

1. Create a model with `timestamps` option to true
2. Add an item to the table using `.create`

### source

```ts
import { connect } from "trilogy";

export default async function test() {
  const db = connect("test.sqlite");

  const model = await db.model(
    "tests",
    {
      id: "increments",
      item: String,
    },
    { timestamps: true }
  );

  await model.create({ item: "test" });
}

test();

```

### error

```
(node:3784) UnhandledPromiseRejectionWarning: Error: INSERT OR IGNORE into `tests` (`item`) values ('test') - SQLITE_ERROR: no such column: new.created_at
```

## expected

Timestamps should create `updated_at` and `created_at` columns on the `test` table.

## actual

The timestamp columns are not created. There's instead a `tests_returning_temp` table that has the correct columns, but not the correct types.

I can get around this by defining my own `createdAt` proeperty, but that's kinda leaving me to do the work that should already be here. I couldn't find out exact bugs, but when defining my own property, I did successfully create an entry. I suspect this is a knex issue since I saw something about timestamps bug something on their github issues page.

Here is that resulting schema that is produced:
![schema](https://user-images.githubusercontent.com/55610086/128356832-7ad9e91b-3038-4f53-a56b-149e1c26b289.png)

**Comment by c43721** [comment]
I am adding a better example here, as I am able to reproduce for realsies here.

Tested with:
```
    "sqlite3": "^5.0.2",
    "trilogy": "^2.0.3"
```

**Comment by c43721** [comment]
I also can recreate this using a test on the trilogy library (which btw won't build on anything other than node version 8?)

Test:
```ts
test('create: handles timestamps', async t => {
  const [one, two] = await Promise.all([
    db.model('test_one', {
      name: { type: String, defaultTo: 'sally' }
    }, {
      timestamps: true 
    }),
    db.model('test_two', {
      name: { type: String, defaultTo: 'bob' }
    }, {
      timestamps: true 
    })
  ])

  await t.notThrowsAsync(one.create({}))
  await t.notThrowsAsync(two.create({}))

})
```

expect:
test to pass

actual:
![test fails](https://user-images.githubusercontent.com/55610086/128610261-1fe94890-0aba-45d1-8d17-2e26d5e8d546.png)

**Comment by citycide** [comment]
This was a fun little bug, interesting it hasn't popped up before now 🤣. Some off logic in the table creation was preventing the options (including timestamp creation) from being processed properly in a couple cases.

`v2.0.5` should resolve this for you.

> the trilogy library (which btw won't build on anything other than node version 8?)

I can't repro that even during recent changes using Node 16.x (plus the existing test matrix). If you still run into it, see if you can come up with a repro case.

**Comment by c43721** [comment]
Thanks!

I think there's some issues when installing on Windows with sql.js, I'll try my hands to see if it builds in wsl. I got it to build anyways using node 8, but was just odd. Again, thanks a lot for the help!
