### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by VladShcherbin** [citycide/trilogy#19]
Hey, what's about migrations mechanism?

**Comment by citycide** [comment]
I don't currently have any implementation in mind for migrations. I've never used them, so I don't know entirely how it would work.

It's something I can explore in the future, and PRs would definitely be welcome.

**Comment by citycide** [comment]
I mean, in general it's just altering the table, transforming the objects in that table to that new schema, and then reinserting those objects - is that right?

**Comment by VladShcherbin** [comment]
Yes, traditionally a single migration has `up` and `down` sections which transform to queries.
`up` query is executed when you run the migration, `down` query is executed when you rollback.
Usually, `migrations` table is created in database to keep track of executed migrations.

From someone's tutorial (knex):

```js
exports.up = function(knex, Promise) {  
  return Promise.all([
    knex.schema.createTable('users', function(table){
      table.string('username');
      table.string('password');
      table.timestamps();
    })
  ])
};

exports.down = function(knex, Promise) {  
  return Promise.all([
    knex.schema.dropTable('users');
  ])
};
```

I also saw another interesting way of doing this - [dexie versions](https://github.com/dfahlander/Dexie.js/wiki/Design#database-versioning), it can be a source of inspiration.

All in all, I think it's probably easier to stick with traditional way (up/down/migrations table) since knex is used internally.

**Comment by citycide** [comment]
Coming back and thinking about this I'm pretty sure you could just use the underlying knex instance to manage migrations.

```js
db.knex.migrate.make(name, {})
```

**Comment by VladShcherbin** [comment]
@citycide yeah, `knex` underlying instance can be used for this. So, there is actually migrations support ;)

**Comment by ram-you** [comment]
Hi @citycide and @vladshcherbin ,
have you please a working example with **db.knex.migrate** ?
Thanks.

**Comment by citycide** [comment]
@ram-you sorry I haven't used them but you should be able to use it basically the same as any knex tutorial or documentation does. Maybe @vladshcherbin can pitch in here and be more helpful than I am.

I'd accept a PR to add documentation for this.

**Comment by vladshcherbin** [comment]
@ram-you hey, I'm using knex migrations same way like I've posted above (and in knex docs):

Here is a basic migration file

```js
exports.up = knex => (
  knex.schema.createTable('users', (table) => {
    table.increments('id')
    table.string('email', 100).notNullable().unique()
    table.string('password', 80).notNullable()
    table.timestamp('created_at').notNullable()
    table.timestamp('updated_at').notNullable()
  })
)

exports.down = knex => (
  knex.schema.dropTable('users')
)
``` 

Then I run them using [knex migrations cli](https://knexjs.org/#Migrations-CLI):

```console
knex migrate:latest
knex migrate:rollback
```

**Comment by ram-you** [comment]
Thank you both.
