### ISSUE TITLE
[question] how to perform WHERE and AND clauses using find method ?

### ISSUE THREAD

**Issue by kmsheng** [citycide/trilogy#54]
https://trilogy.js.org/#/api?id=find
```
Array syntax is either a key / value pair (equal to) or a length of 3,
 ie. ['age', '<', 65] (allows other comparisons)
```

For example, if I want to select where age is less than 65 and sex is male

**Comment by citycide** [comment]
Multiple clauses isn't really covered in the current API but I'd definitely like to add it now that you mention it. Initial reaction is to have a new method for it, to avoid ambiguity and too much overload of `find`'s signature... something like:

```js
model.findWhere([column], [...criteria], [options])
```

where `criteria` is an Array of the Arrays / Objects that `find` accepts.

```js
people.findWhere([
  ['age', '<', 65],
  { sex: 'male' }
]).then(found => {})
```

Thoughts on the method name are welcome.

* `findWhere`
* `findBy`
* `findWith`
... etc

**Comment by kmsheng** [comment]
I have no preference for the method name,  but the query builder should be chainable.
Most of the ORMs I know they do something like:
```
people.findWhere(['age', '<', 65])
  .andWhere({sex: 'male'})
  .orWhere({career: 'engineer'});
```

https://forum.phalconphp.com/discussion/12155/querybuilder-orwhere-inside-andwhere
http://knexjs.org/#Raw-Bindings

**Comment by citycide** [comment]
I specifically built trilogy so that it would not have a chainable API. If you want to use a chainable API you can use [`db.raw()`](https://trilogy.js.org/#/api?id=raw) with `knex` queries, which is easy enough, or just use `knex` by itself.

**Comment by kmsheng** [comment]
Ok. No problem.

**Comment by citycide** [comment]
This is possible in [v1.2.0](https://github.com/citycide/trilogy/releases/tag/v1.2.0) ( without a new method ) anywhere that accepts `criteria`:

```js
people.find([
  ['age', '<', 65],
  { sex: 'male' }
]).then(found => {})
```

It's just an Array of any number of the other forms of where clause. This covers `and where` - things like `or` and combinations of logical chains I think I'll leave to `db.raw()` and `knex` queries.

Thanks for filing!
