### ISSUE TITLE
Support schema getters & setters

### ISSUE THREAD

**Issue by kmsheng** [citycide/trilogy#56]
It would be nice if column getter is available.
```js
db.model('people', {
  name: String,
  age: Number,
  email: String,
  uid: {
    type: Number,
    primary: true,
    get: (value) => `myCustomPrefix-${value}`
  }
})
```

**Comment by citycide** [comment]
Could you explain a little more about the use case? Would this act as a hook to alter the value returned from a select query, without changing what's stored?

ie. is the current equivalent pulling `uid` and doing something like `` `myCustomPrefix-${uid}` `` ?

**Comment by kmsheng** [comment]
Yes, this does not change the actual values in db, it only calls the getter after the data is fetched from db.

https://github.com/karmapa17/garchen-panel/blob/ticket743/src/main/models/entry.js
My situation is a little awkward : /
I am creating a dictionary creation tool,  there's a model called `entry` which stores the entries of a dictionary. I need to add a `page-num` field, so users can add their page number of a entry.

Page number "1.10" represents the entry is located at the first page and the 10th entry, 
so "1.2" would be the first page and the second entry. Sqlite won't sort my page number column in correct ASC or DESC order unless I fill my fraction part with leading zeros.
For example, "1.10" and "1.02" would be sorted correctly. 

So the use case would be,
I have to store values filled with leading zeros in db.
But the interface text only needs the values that have leading zeros removed.

My setter of `page-num` would convert `1.2` to `1.02` before insertion of an entry data.
My getter of `page-num` would convert `1.02` to `1.2` after the entry data is fetched from db.

If this conversion is written in user-land, it would be duplicated a lot which is not DRY.

Another similar usage can be found here:
http://docs.sequelizejs.com/manual/tutorial/models-definition.html#getters-setters

**Comment by citycide** [comment]
Seems like a solid case for getters & setters, thanks for that.

**Comment by citycide** [comment]
@kmsheng also I'm glad to see trilogy in use by someone 😅 thanks for the link.

**Comment by citycide** [comment]
@kmsheng this is available in `1.3.0-beta.1` if you want to try it out 😄. You'll have to `npm i trilogy@next`.

**Comment by kmsheng** [comment]
@citycide Thanks for helping me, man. I will make a new refactoring branch for my project based on this.

**Comment by citycide** [comment]
Released in [v1.3.0](https://github.com/citycide/trilogy/releases/tag/v1.3.0)

**Comment by kmsheng** [comment]
@citycide I found out that the value was casted before setter is fired. Please see my test.
https://github.com/karmapa17/trilogy/commit/9aa7bf8b8b701c2799e616e094d9e3ae45c3d4ef

**Comment by citycide** [comment]
@kmsheng good call, that's an easy fix. 👍
