### ISSUE TITLE
Unable to define multiple indices via the same table

### ISSUE THREAD

**Issue by kmsheng** [citycide/trilogy#68]
Something like this would be nice, or provide an option to let user define their multiple indices
```js
  db.model('people', schema, (table) => {
      table.index(['col1', 'col2'])
        .index(['col2', 'col3'])
        .unique(['somethingUnique']);
  }); 
```

**Comment by citycide** [comment]
Are you referring to the table constructor callback or to the `index` and `unique` methods? Multiple `unique` columns is already possible by doing this:

```js
db.model('people', schema, {
  unique: ['name', 'email']
})
```

See the docs here for those options: https://trilogy.js.org/#/api?id=model. `index` is definitely possible to support there, looks like it can be handled the same exact way as `unique` and `primary` are in the model options.

**Comment by kmsheng** [comment]
Yes, it's possible to have multiple indices on multiple columns.
For example you can do
```
create index index_name1 on YOUR_TABLE_NAME(col1, col2);
create index index_name2 on YOUR_TABLE_NAME(col1, col2);
```

and then
```
select * from sqlite_master where type = 'index'
;
```
to check your existed indices

**Comment by kmsheng** [comment]
also you can run `explain query plan` to check if your index is applied actually.

**Comment by citycide** [comment]
Awesome, let's get this added. 👍
