### ISSUE TITLE
Add TypeScript/Flowtype definitions

### ISSUE THREAD

**Issue by oyekeno** [citycide/trilogy#7]
I'm sorry if i'm being too noob here, but i cant import this module to any ts file.
I get an error that says that it cant find it. That it needs a definition(or declarations?) file.

Sorry and thanks in advance. 
(Also, could you please link me to a repo of a working example so i can learn from it? Thanks!)

**Comment by citycide** [comment]
That's (mostly) a TypeScript issue, in the sense that if you were using plain JS this wouldn't be a problem. It can be solved by writing a definition file - [check out the DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped) for examples of this. I'm personally not a big fan of TS myself, trilogy uses [flow](https://github.com/facebook/flow) but still doesn't expose a definition file.

I think there's a way to just type your import as `any` but if you're using TS that kind of defeats the purpose.  As for the definitions, feel free to contribute as I'm not sure when I'll get to it.

**Comment by citycide** [comment]
Added initial TypeScript definitions in 3d9a2a5 - not published to npm yet though. Still looking into Flow types.

**Comment by citycide** [comment]
TypeScript & Flow definitions are now available and published as of [v1.2.0](https://github.com/citycide/trilogy/releases/tag/v1.2.0).
