### ISSUE TITLE
No default export and error instantiating Trilogy

### ISSUE THREAD

**Issue by YagoLopez** [citycide/trilogy#83]
Hello.

- I'm trying a trivial example of Trilogy with 'sql.js':

```javascript
import Trilogy from 'trilogy';

const db = new Trilogy(':memory:', {
  // it works for both clients above!
  client: 'sql.js'
});
```
but get this error:

```
Failed to compile
C:/Users/yagol/Documents/projects/sql_js-test/src/index.tsx
(4,8): Module '"C:/Users/yagol/Documents/projects/sql_js-test/node_modules/trilogy/dist/trilogy"' has no default export.

Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_trilogy___default.a is not a constructor
    at Object../src/index.tsx (index.tsx:7)
    at __webpack_require__ (bootstrap afab123b749fe6c9a0c4:678)
    at fn (bootstrap afab123b749fe6c9a0c4:88)
    at Object.0 (index.tsx:16)
    at __webpack_require__ (bootstrap afab123b749fe6c9a0c4:678)
    at ./node_modules/ansi-regex/index.js.module.exports (bootstrap afab123b749fe6c9a0c4:724)
    at bootstrap afab123b749fe6c9a0c4:724
index.js:2177 C:/Users/yagol/Documents/projects/sql_js-test/src/index.tsx
(4,8): Module '"C:/Users/yagol/Documents/projects/sql_js-test/node_modules/trilogy/dist/trilogy"' has no default export.
__stack_frame_overlay_proxy_console__ @ index.js:2177
```

- After trying to import whitout default imports:

```javascript
import {Trilogy} from 'trilogy'; // note the brakets
```
I get the error:

```
TypeError: __WEBPACK_IMPORTED_MODULE_0_trilogy__.Trilogy is not a constructor
./src/index.tsx
C:/Users/yagol/Documents/projects/sql_js-test/src/index.tsx:7
   4 | import {Trilogy} from 'trilogy';
   5 | // declare var Trilogy: any;
   6 | 
>  7 | const db = new Trilogy(':memory:', {
   8 |   // it works for both clients above!
   9 |   client: 'sql.js'
  10 | });



Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_trilogy__.Trilogy is not a constructor
    at Object../src/index.tsx (index.tsx:7)
    at __webpack_require__ (bootstrap 270ce0d30a7f6fb8b756:678)
    at fn (bootstrap 270ce0d30a7f6fb8b756:88)
    at Object.0 (index.tsx:16)
    at __webpack_require__ (bootstrap 270ce0d30a7f6fb8b756:678)
    at ./node_modules/ansi-regex/index.js.module.exports (bootstrap 270ce0d30a7f6fb8b756:724)
    at bootstrap 270ce0d30a7f6fb8b756:724
```

- Note:
**I'm using create-react-app-typescript (that is, reactjs + webpack + typescript)**

**Comment by YagoLopez** [comment]
Problems are probably due to module imports, webpack and typescript. Type definitions could have some errors or incompatiblities with create-react-app for typescript. In some way I could get it working deleting `trilogy.d.ts` and importing Trilogy with `require()` and found a small bug in a example. I Opened a PR, hope it helps. Im very interested in this project for using sql.js in browser.

In the future I could upload my project to github for your review.

**Comment by citycide** [comment]
Hey @YagoLopez thanks for reporting. I hope to look into this a little deeper soon but unfortunately this week will be a little busy for me.

v2 should fix all the TypeScript incompatibilities since trilogy itself is written in TS now. I'd like to merge & release that fairly soon but still hoping for some 3rd party review and feedback. Worth noting that it's available on npm if you use `npm i trilogy@next`. If you're also using TS you'll get better code suggestions using that, see [here](https://github.com/citycide/trilogy/pull/82) _("getting TypeScript compiler assistance on models")_.

I'll also take a look at usage in Webpack. Definitely if you're able to put a repro on GitHub I could pull down that'd be super 👍

**Comment by YagoLopez** [comment]
Ok no hurry. take your time. I'll be waiting for next version and put online an example of create-react-app with webpack and typescript.
