### ISSUE TITLE
[v2.0.0-rc.1] error

### ISSUE THREAD

**Issue by ram-you** [citycide/trilogy#92]
Hi,
switched from beta2 to v2.0.0-rc.1, change : 
from **import { create } from 'trilogy'** to **import { connect } from 'trilogy'**
Receive this error:

> Uncaught (in promise) TypeError: (0 , _trilogy.connect) is not a function

The problem appears when package installed via : `npm i trilogy@2.0.0-rc.1`
 and disappears when done via :  `npm i trilogy@next`

I think it's a package compilation problem.

**Comment by citycide** [comment]
@ram-you bummer I'll check it out, thanks!

**Comment by citycide** [comment]
Ah, it's because the `prepublishOnly` script runs the tests but the tests no longer have to pre-build TypeScript. Easy fix.

**Comment by citycide** [comment]
Fixed in `2.0.0-rc.2`

**Comment by ram-you** [comment]
Sorry for inconvenient, I switched to 2.0.0-rc.2, and now we have new  error .

Although I did not mention in my code "**create**" but rather "**connect**" like this:

```
import {connect} from 'trilogy'
const db = connect (': memory:')
```

The error:

> Uncaught (in promise) TypeError: (0, _trilogy.create) is not a function

**Comment by citycide** [comment]
I can't repro in a freshly made project. Try things like `npm cache clean` or delete the entire `node_modules` directory and reinstall, and make sure you've installed the most recent version of trilogy using `trilogy@2.0.0-rc.2`.
