### ISSUE TITLE
Awesome Electron

### ISSUE THREAD

**Issue by ram-you** [citycide/trilogy#93]
Hi,
Please add **Trilogy** to "**Awesome Electron**" _(15,200 stars)_ to increase visibility (users).
Thank you.

https://github.com/sindresorhus/awesome-electron/issues/548

**Comment by citycide** [comment]
I'll add it but now's not a great time just because the TS rewrite isn't out yet and if trilogy's going to be on that list I'd like to note that it's a well-typed TS library. Let's wait until v2 drops.
