### ISSUE TITLE
sqljs usage changes

### ISSUE THREAD

**Issue by linonetwo** [citycide/trilogy#96]
https://github.com/citycide/trilogy/blob/506126c4f4e626a36c48f0d2cf50c34bea07c66c/src/sqljs-handler.js#L8

https://github.com/kripken/sql.js/issues/270#issuecomment-491743275

**Comment by linonetwo** [comment]
Causing https://github.com/citycide/trilogy/issues/95

**Comment by citycide** [comment]
Duplicate of #95
