### ISSUE TITLE
Issue while using with angular 8 and electron 

### ISSUE THREAD

**Issue by mraj8** [citycide/trilogy#97]
![image](https://user-images.githubusercontent.com/36467998/62898583-7860a880-bd73-11e9-8f95-13089cdd203e.png)

Cannot find module 'sql.js/module'. 

![image](https://user-images.githubusercontent.com/36467998/62898697-bb228080-bd73-11e9-8373-623b7a069c09.png)
Module not found: Error: Can't resolve 'mssql/package.json'

I am trying to build a electron App with angular and triology

i tried connecting sqlite database by using both sql js and sqlite

**Comment by citycide** [comment]
@mraj8 please use the issue template.

I don't have a lot of time to dig into this right now but a repo that reproduces the issue would help me or anyone who'd like to check this out.

**Comment by citycide** [comment]
Since I wasn't able to reproduce and haven't received any more info I'm going to close, but feel free to reopen if this is still an issue.
