### ISSUE TITLE
Can find accecpts Array?

### ISSUE THREAD

**Issue by bodhi-ma** [citycide/trilogy#98]
Assume thers are [{id:1,name:"1"},{id:2,name:"2"},{id:3,name:"3"}] in db. I want to find out the items whoes id is 1 or 2, how can I do that?
Can the sytax be like mongodb, just as model.find({id:{$in:[1,2]}})?

**Comment by citycide** [comment]
Hi @bodhi-ma, currently only `and` is supported with multiple criteria, so you'd have to express this in a way that's compatible with that, i.e. where `id` is greater than/equal to 2 AND less than/equal to 3:

```js
people.find([
  ["id", ">=", 2],
  ["id", "<=", 3]
])
```

I don't particularly like the mongo syntax for those operators, and I've been meaning to come up with a way to do what you ask for a while. Very open to suggestions, always thought something roughly like these but the types would need some work:

```js
import { ops } from 'trilogy'

people.find([
  ops.or({ id: 2 }, { id: 3 }),
])

// or

people.find([
  { id: ops.any([1, 2]) }
])

// ¯\_(ツ)_/¯
```

**Comment by bodhi-ma** [comment]
OK, seems great. Waiting for the upgrading.
