### ISSUE TITLE
Knex: run$ npm install sqlite3 --saveCannot find module 

### ISSUE THREAD

**Issue by yanlee26** [citycide/trilogy#99]
I used it like this:

```
const db = connect('./store.db', {
  client: 'sqlite3'
})
```

in MacOS and the error is: 

`
Knex: run$ npm install sqlite3 --saveCannot find module '/Users/elliotyan/Documents/me/electron-with-sqlite3/node_modules/sqlite3/lib/binding/electron-v8.2-darwin-x64/node_sqlite3.node'Require stack:- /Users/elliotyan/Documents/me/electron-with-sqlite3/node_modules/sqlite3/lib/sqlite3-binding.js- /Users/elliotyan/Documents/me/electron-with-sqlite3/node_modules/sqlite3/lib/sqlite3.js- /Users/elliotyan/Documents/me/electron-with-sqlite3/node_modules/knex/lib/dialects/sqlite3/index.js- /Users/elliotyan/Documents/me/electron-with-sqlite3/node_modules/knex/lib/knex.js- /Users/elliotyan/Documents/me/electron-with-sqlite3/node_modules/knex/lib/index.js- /Users/elliotyan/Documents/me/electron-with-sqlite3/node_modules/knex/knex.js- /Users/elliotyan/Documents/me/electron-with-sqlite3/node_modules/trilogy/dist/index.js- /Users/elliotyan/Documents/me/electron-with-sqlite3/preload.jsError: Cannot find module '/Users/elliotyan/Documents/me/electron-with-sqlite3/node_modules/sqlite3/lib/binding/electron-v8.2-darwin-x64/node_sqlite3.node'`

**Comment by citycide** [comment]
@yanlee26 I'd be glad to help, but you'll have to provide more information. Please use the issue template next time.

Did you install the `sqlite3` module like the error message says?

```sh
npm install sqlite3
```

**Comment by citycide** [comment]
I'm going to close due to lack of info and response. Please reopen if you can still reproduce the issue and provide the information required to debug it.
